actions=(
    '30 deep bends + sholder rolls'
    '30 neck rolls'
    '30 neck rolls (change direction)'
    '60 neck pull'
    '60 neck pull (swap sides)'
    '30 arm swings (horizontal)'
    '60 cross shoulder'
    '60 cross shoulder (swap sides)'
    '60 overhead triceps'
    '60 overhead triceps (swap sides)'
    '30 deep bends + sholder rolls'
    '60 touch toes (feet wider than sholders)'
    '30 hold squat'
    '60 swing side to side'
    '60 touch one foot'
    '60 touch one foot (swap sides)'
    '60 touch toes (feet slightly narrower than sholders)'
    '60 pop heels'
    '30 squat into touch toes (go further)'
    '60 butterfly pose'
    '60 push hands on knees'
    '60 lean forward (back straight)'
    '60 lean forward (curl back)'
    '60 extend one leg to side and reach with opposite arm (look up)'
    '60 hurdler (both hands)'
    '60 extend one leg to side and reach with opposite arm (look up, swap sides)'
    '60 hurdler (both hands, swap sides)'
    '180 straddle'
    '30 knee hug'
    '45 knee to chest'
    '90 hamstring'
    '45 pull other leg to the side'
    '45 cross leg over'
    '45 knee to chest (swap sides)'
    '90 hamstring (swap sides)'
    '45 pull other leg to the side (swap sides)'
    '45 cross leg over (swap sides)'
    '60 figure four'
    '60 figure four (swap sides)'
    '60 lunging hip flexor'
    '60 drop other knee to ground keep leg horizontal'
    '60 bring foot closer to chest to bring head down'
    '60 lunging hip flexor (swap sides)'
    '60 drop other knee to ground keep leg horizontal (swap sides)'
    '60 bring foot closer to chest to bring head down (swap sides)'
    '180 pigeon pose'
    '60 make a c with your back'
    '60 childs pose with reach'
)
