actions=(
    '60 plank knee twists'
    '60 wide push-ups'
    '60 shoulder taps'
    '60 mountain climbers'
    '60 toe cross overs'
    '60 heel touches'
    '30 rest'
    '60 ab crunch'
    '60 russian twists'
    '60 burpees (no push-up)'
    '60 toe jumps'
    '60 lunge jumps'
    '30 rest'
    '60 oblique crunch'
    '60 oblique crunch (swap sides)'
    '60 rotating punch'
    '60 v ins'
    '60 plank ups'
    '60 lunge ups (moving backwards)'
    '60 lunge ups (swap sides)'
    '60 high knees'
)
