legacy_layout=0

cpu_stats
cpu_temp
core_load
ram
gpu_stats
gpu_temp
gpu_power
vram
fps
frame_timing
present_mode

round_corners=10
background_alpha=0.8
background_color=1E1E2E
font_size=24
text_color=CDD6F4
text_outline_color=313244
gpu_color=A6E3A1
cpu_color=89B4FA
ram_color=F5C2E7
frametime_color=A6E3A1
