monitorrule = name:^eDP-1$, width:2560, height:1600, refresh:60, x:0, y:0, scale:1, vrr:0, hdr:0, rr:0, custom:0, disable:0

exec-once = fcitx5
exec-once = nm-applet
exec-once = quickshell -n

exec-once = swayidle -w \
  before-sleep 'loginctl lock-session' \
  lock 'pidof hyprlock || hyprlock' \
  timeout 270 'brightnessctl -s set 0% && asusctl -k off' resume 'brightnessctl -r' \
  timeout 300 'loginctl lock-session' resume 'brightnessctl -r' \
  timeout 330 'systemd-ac-power || systemctl suspend'

xkb_rules_layout = gb
xkb_rules_options = caps:escape

mouse_accel_profile = 0

trackpad_natural_scrolling = 1

drag_tile_small = 0
drag_corner = 0
drag_warp_cursor = 0

borderpx = 2
gappih = 6
gappiv = 6
gappoh = 12
gappov = 12

rootcolor=0x313244ff
bordercolor = 0x313244ff
focuscolor = 0xf5c2e7ff
globalcolor = 0xf5c2e7ff

cursor_size=24
cursor_theme=catppuccin-mocha-dark-cursors

border_radius = 6

blur = 0
shadows = 0

animations = 0

tagrule = id:*, layout_name:tile

new_is_master = 0
default_mfact = 0.5

windowrule = appid:^blueman-manager$, isfloating:1, isglobal:1, width:600, height:480, offsetx:99, offsety:-98
windowrule = appid:^com.saivert.pwvucontrol$, isfloating:1, isglobal:1, width:600, height:480, offsetx:99, offsety:-98
windowrule = appid:^org.quickshell$, isfloating:1
windowrule = appid:^protonvpn-app$|^proton.vpn.app.gtk$, isfloating:1, isglobal:1, width:600, height:480, offsetx:-99, offsety:-98

ov_tab_mode = 0

bind = SUPER, q, killclient
bind = SUPER, w, spawn, hyprshot -m window
bind = SUPER, e, spawn, thunar
bind = SUPER, r, spawn, hyprshot -m region

bind = SUPER, f, togglefullscreen
bind = SUPER, RETURN, spawn, foot

bind = SUPER, b, spawn, helium-browser
bind = SUPER, n, spawn, foot -e nvim
bind = SUPER, m, zoom

bind = SUPER, SPACE, spawn, bemenu-run -C -i -l 10 -p $ -T --fixed-height --single-instance -c -W 0.25 -B 2 -R 8

bind = SUPER, 1, view, 1
bind = SUPER, 2, view, 2
bind = SUPER, 3, view, 3
bind = SUPER, 4, view, 4
bind = SUPER, 5, view, 5

bind = SUPER, h, focusdir, left
bind = SUPER, j, focusdir, down
bind = SUPER, k, focusdir, up
bind = SUPER, l, focusdir, right

bind = SUPER + SHIFT, 1, tag, 1
bind = SUPER + SHIFT, 2, tag, 2
bind = SUPER + SHIFT, 3, tag, 3
bind = SUPER + SHIFT, 4, tag, 4
bind = SUPER + SHIFT, 5, tag, 5

bindl = SUPER + SHIFT, r, spawn_shell, powerprofilesctl set power-saver; asusctl armoury set panel_overdrive 0; systemctl reboot
bindl = SUPER + SHIFT, o, spawn_shell, powerprofilesctl set power-saver; asusctl armoury set panel_overdrive 0; loginctl terminate-session ''
bindl = SUPER + SHIFT, p, spawn_shell, powerprofilesctl set power-saver; asusctl armoury set panel_overdrive 0; systemctl poweroff

bindl = SUPER + SHIFT, s, spawn_shell, systemd-ac-power || systemctl suspend
bindl = SUPER + SHIFT, d, spawn, brightnessctl set 1%
bind = SUPER + SHIFT, g, spawn, ~/.config/mango/toggle-dgpu.sh
bind = SUPER + SHIFT, l, spawn, loginctl lock-session

bindl = SUPER + SHIFT, b, spawn, brightnessctl set 50%

bindl = NONE, XF86AudioLowerVolume, spawn, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = NONE, XF86AudioRaiseVolume, spawn, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindl = NONE, XF86AudioMicMute, spawn, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl = NONE, XF86AudioMute, spawn, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = NONE, XF86KbdBrightnessDown, spawn, asusctl leds prev
bindl = NONE, XF86KbdBrightnessUp, spawn, asusctl leds next
bindl = NONE, XF86Launch1, spawn, ~/.config/mango/toggle-game-mode.sh
bindl = NONE, XF86Launch3, spawn, asusctl aura power keyboard --awake; asusctl aura effect static --colour f5c2e7
bindl = NONE, XF86Launch4, spawn, ~/.config/mango/next-performance-mode.sh
bindl = NONE, XF86MonBrightnessDown, spawn, brightnessctl set 5%-
bindl = NONE, XF86MonBrightnessUp, spawn, brightnessctl set 5%+
