general:lock_cmd = echo lock | socat - UNIX-CONNECT:/tmp/quickshell.sock
general:before_sleep_cmd = loginctl lock-session

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 0% && asusctl -k off && loginctl lock-session
    on-resume = brightnessctl -r
}

listener {
    timeout = 330
    on-timeout = systemd-ac-power || systemctl suspend
}
