general:lock_cmd = echo lock | socat - UNIX-CONNECT:/tmp/quickshell.sock
general:before_sleep_cmd = loginctl lock-session

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 0%; asusctl leds set off; systemd-ac-power && loginctl lock-session || systemctl suspend
    on-resume = brightnessctl -r
}
